global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'calculator-monitor'

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets:
          - 'otel-collector:9464'